### ISSUE TITLE
Observations & Enhancements 

### ISSUE THREAD

**Issue by aogaili** [gauravchl/react-image-story#1]
I really like this component and I think it's very well executed and I'd like to use on my project.  However I found some corner cases and issues that needs to be addressed in addition to the items listed in the TODO list. 

Here are my observations thus far:

1. If you supply exactly two images, the images won't render and you will get the following error:
` NaN is an invalid value for the `height` css style property. Check the render method ImageStory`
_[Edit: actually I'm unable to replicate this so I'm doing more testing]_ 

2. If you don't supply a callback for `onImageSelect` and you click on an image, you'll get the following  error: `Uncaught TypeError: r is not a function`

3. The component expects a prop of type number however this could be restrictive. You can't pass a string like width='100%' to make it responsive.
 _[Edit: it seems that it does take a string, the only issue is the react warning on props validation
`Warning: Failed prop type: Invalid prop `width` of type `string` supplied to `ImageStory`, expected `number``.]_ 

4. If `onImageSelect` has been provided  and you hover on an image, then it will be nice to show a hand cursor
_[Edit: I'm able to get the desired behaviour by using   `rootStyle={{ cursor: 'pointer' }}`]_

I hope we can address those to make it fully polished :)

**Comment by gauravchl** [comment]
@aliogaili This is great, thanks! 
I'll soon try to fix those issues.

**Comment by gauravchl** [comment]
@aliogaili All issues addressed in v0.1.0 except:
> If you supply exactly two images, the images won't render and you will get the following error

Is it still bothering?

**Comment by aogaili** [comment]
That's great @gauravchl much appreciated! I'll test and let you know soon what I observe.

**Comment by aogaili** [comment]
I'm still having issues with passing the width property. If I put `width='100%'`, react throws an error:

`Failed prop type: Invalid prop `width` of value `100%` supplied to `ImageStory`, expected one of [null,null].`

I think it has to do with this [line](https://github.com/gauravchl/react-smart-gallery/blob/master/src/index.jsx#L10) and it might be fixed by following the suggestion [here](https://github.com/gauravchl/react-smart-gallery/blob/master/src/index.jsx#L10) 

If I supply two images, I get the following error: 

```
Warning: `NaN` is an invalid value for the `height` css style property. Check the render method of `ImageStory`.
```
and the images won't render, in my testes hardcoded those values and it works well.

**Comment by aogaili** [comment]
Hello @gauravchl  would be you tackling this last issue? I'm using a local fork of the library because of this last one.

**Comment by gauravchl** [comment]
Hi @aliogaili, Sorry i almost missed it.
I've applied the fixes in v0.1.1 Please review the new updates. 
Thanks.

**Comment by aogaili** [comment]
Great! thank you so much @gauravchl, I'll give it a spin and let you know :)

**Comment by aogaili** [comment]
@gauravchl the component is working perfectly now! great work buddy, thanks for responding to my issues.
